name: Go CI

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'go/**'
  pull_request:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'go/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install dependencies
        run: cd go && go mod download

      - name: Run t
