name: WordPress CI

on:
  push:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'wordpress/**'
  pull_request:
    branches:
      - main
      - 'feature/*'
    paths:
      - 'wordpress/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@
